### ISSUE TITLE
Getting kicked from server

### ISSUE THREAD

**Issue by GiraffeSummer** [Corgam/CagedMobs#27]
Hello, I keep getting kicked from my server, I checked the logs and the reason seems to be:

```
[13:11:38] [Render thread/ERROR]: Error getting cached entity!
java.lang.NullPointerException: null
	at com.corgam.cagedmobs.tileEntities.MobCageTE.getCachedEntity(MobCageTE.java:82) [?:1.16.4-1.2.6]
	at com.corgam.cagedmobs.tileEntities.MobCageRenderer.render(MobCageRenderer.java:54) [?:1.16.4-1.2.6]
	at com.corgam.cagedmobs.tileEntities.MobCageRenderer.func_225616_a_(MobCageRenderer.java:32) [?:1.16.4-1.2.6]
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228855_a_(TileEntityRendererDispatcher.java:101) [?:?]
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.lambda$renderTileEntity$0(TileEntityRendererDispatcher.java:85) [?:?]
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher$$Lambda$29064/1417189218.run(Unknown Source) [?:?]
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:118) [?:?]
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:84) [?:?]
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1043) [?:?]
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:607) [?:?]
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.36.jar:35.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$491/905654793.call(Unknown Source) [forge-1.16.4-35.1.36.jar:35.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?]
```

Is there any way to fix this, or can you do anything about it?

**Comment by Corgam** [comment]
I think it should be fixed after latest update, let me know if it is still a problem!
